name: General
main: net.craftstars.general.General
authors:
  - Celtic Minstrel
  - Plutonium239
  - Nijikokun
version: 3.0
commands:
  playerlist:
    description: Displays all players that are online.
    permission: general.playerlist
    aliases:
      - online
    usage: |
           /<command>
           Example: /<command> - Lists all online players.
  who:
    permission:
    description: Displays information about a player.
    aliases: [whoami, playerinfo]
    usage: |
           /<command> [player]
           Example: /<command> - Gives information about you.
           Example: /<command> [player] - Gives information about [player]
  time:
    permission:
    description: Displays or modifies current world time.
    aliases:
    usage: |
           /<command> [day|night|dusk|dawn|=num|+num|-num] [world]
           Example: /<command> - Gets current time.
           Example: /<command> day - Sets time to day.
           Example: /<command> night - Sets time to night.
           Example: /<command> dusk - Sets time to dusk.
           Example: /<command> dawn - Sets time to dawn.
           Example: /<command> +500 - Sets relative time forward.
           Example: /<command> -500 - Sets relative time backward.
           Example: /<command> =500 - Sets relative time equal to.
  give:
    permission:
    description: Users to give yourself or another player an item.
    aliases:
      - i
      - item
    usage: |
           /<command> [player] item[:data] [amount]
           item   --> Either the ID of an item, or a known name for it; no spaces
           data   --> The damage value of a tool, the data value of the item, or a known name for the data value
           amount --> How much to get; 1 is default, 0 means a full stack
  getpos:
    permission:
    description: Displays detailed information about your position.
    aliases:
      - compass
      - where
      - pos
      - coords
    usage: /<command> [compass|coords]
  tell:
    permission:
    description: Sends another player a private message.
    aliases:
      - msg
      - pm
      - whisper
    usage: /<command> <player> <message>
  spawn:
    permission:
    description: Teleports you to the spawn location of your current world.
    aliases: [setspawn]
    usage: |
           /<command> [player]           - Teleports you or another player to spawn.
           /<command> set                - Sets spawn to your current location.
           /<command> set player         - Sets spawn to the current location of the specified player.
           /<command> [world] set x y z  - Sets spawn to the specified location.
           /<command> [world] show       - Displays the current spawn location
           /setspawn player
           /setspawn [world] x y z
           The parameters in brackets are optional unless the command is used from the console.
  teleport:
    permission:
    description: Teleports a/multiple/all player(s) to another players location.
    aliases: [tp]
    usage: |
           /<command> [player|player,player,...|*] player
           /<command> [player] - Teleports you to player.
           /<command> [player] [player2] - Teleports player to player2.
           /<command> * [player] - Teleport everyone to player.
           /<command> [player,player,...] player - Teleport several to player.
           /<command> [player] x y z - Teleport you or someone else to a specific location.
  summon:
    permission:
    description: Teleports a player to your location.
    aliases:
      - tphere
      - teleporthere
    usage: /<command> [player]
  clear:
    permission:
    description: Clears your inventory.
    aliases: [clean]
    usage: /<command> [player]
  take:
    permission:
    description: Removes something from your inventory.
    aliases:
    usage: /<command> [player] item[:data] [amount]
  heal:
    permission:
    description: Restores your health. (Can also reduce it if you give a negative amount.)
    aliases:
    usage: /heal [player] [amount]
#  mspawn:
#    permission:
#    description: Spawns a mob.
#    aliases:
#    usage: /mspawn
  general:
    permission:
    description: Administrates the plugin.
    aliases:
    usage: /general reload|die