name: General
main: net.craftstars.general.General
authors:
  - Celtic Minstrel
  - Plutonium239
  - Nijikokun
version: 2.2
commands:
  playerlist:
    description: Displays all players that are online.
    permission: general.playerlist
    aliases:
      - online
    usage: |
           /<command>
           Example: /<command> - Lists all online players.
  who:
    permission:
    description: Displays information about a player.
    aliases:
    usage: |
           /<command> [player]
           Example: /<command> - Gives information about you.
           Example: /<command> [player] - Gives information about [player]
  time:
    permission:
    description: Displays or modifies current world time.
    aliases:
    usage: |
           /<command> [day|night|dusk|dawn|=|+|-]
           Example: /<command> - Gets current time.
           Example: /<command> day - Sets time to day.
           Example: /<command> night - Sets time to night.
           Example: /<command> dusk - Sets time to dusk.
           Example: /<command> dawn - Sets time to dawn.
           Example: /<command> +500 - Sets relative time forward.
           Example: /<command> -500 - Sets relative time backward.
           Example: /<command> =500 - Sets relative time equal to.
  give:
    permission:
    description: Users to give yourself or another player an item.
    aliases:
      - i
      - item
    usage:
  compass:
    permission:
    description: Displays your current compass heading.
    aliases:
    usage:
  getpos:
    permission:
    description: Displays detailed information about your position.
    aliases:
    usage:
  tell:
    permission:
    description: Sends another player a private message.
    aliases:
      - msg
    usage: |
           /<command> <player> <message>
  spawn:
    permission:
    description: Teleports you to the spawn location of your current world.
    aliases:
    usage: /<command>
  teleport:
    permission:
    description: Teleports a/multiple/all player(s) to another players location.
    aliases:
    usage: |
           /<command> [player|player,player,...|*] [player]
           /<command> [player] - Teleports you to player.
           /<command> [player] [player2] - Teleports player to player2.
           /<command> * [player] - Teleport everyone to player.
           /<command> [player,player,...] [player] - Teleport several to player.
  summon:
    permission:
    description: Teleports a player to your location.
    aliases:
      - tphere
      - teleporthere
    usage: |
           /<command> [player]